core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include("django.contrib.auth.urls")),
    path('', include('posts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import DashboardView, AddBlogPost, UpdateBlogPost, PostDetailView, delete_Post, LikeView

app_name= 'posts'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('<int:id>/', PostDetailView.as_view(), name='postDetail'),
    path('<int:id>/update_post', UpdateBlogPost.as_view(), name='postEdit'),
    path('<int:id>/delete_post', delete_Post, name='postDelete'),
    path('<int:id>/like', LikeView, name='like_post'),
    path('add-blog/', AddBlogPost.as_view(), name='add-blog'),
]

users/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from users.views import IndexView, LoginView, LogoutView, RegisterView, ProfileView, ModifyProfileView, followToggle

app_name = 'users'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('login/', LoginView.as_view(), name='login'),
    path('profile/<int:id>/', ProfileView.as_view(), name='profile'),
    path('modifyProfile/', ModifyProfileView.as_view(), name='modifyProfile'),
    path('logout/', LogoutView, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('followToggle/<int:id>/', followToggle, name='followToggle')
]

posts/models.py
from django.db import models
from django.utils import timezone
from users.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name="blog_post")
    picture = models.ImageField(blank=True, null=True, default='defaultBlogPic.png', upload_to='blog_images')

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-date_created']

    def total_likes(self):
        return self.likes.count()

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    class Meta:
        ordering = ['date_added']

posts/forms.py
from django import forms
from posts.models import Post, Comment
from users.models import User

class PostForm(forms.ModelForm):

    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea)
    picture = forms.ImageField(label='Post Image',widget=forms.FileInput)

    class Meta:
        model = Post
        fields = ['title', 'content', 'picture']

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['picture'].required = False

class UpdatePostForm(forms.ModelForm):

    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea)
    picture = forms.ImageField(label='Post Image',widget=forms.FileInput)

    class Meta:
        model = Post
        fields = ['title', 'content', 'picture']
    
    def __init__(self, *args, **kwargs):
        super(UpdatePostForm, self).__init__(*args, **kwargs)
        self.fields['picture'].required = False

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']
    
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateView, View
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.urls import reverse

from django import forms

from .models import Post, Comment, User
from .forms import PostForm, CommentForm, UpdatePostForm
from django.contrib import messages
from pdb import set_trace
# Create your views here.

class DashboardView(TemplateView):
    template_name = 'posts/index.html'

    def get(self, request):
        profile_list = User.objects.all()
        posts = Post.objects.all()
        context = {
            'profile_list' : profile_list,
            'posts' : posts
        }
        return render(request, self.template_name, context)

class AddBlogPost(TemplateView):
    def get(self, request):

        if request.user.is_authenticated:
            addform = PostForm()

            return render(request, 'posts/add-blog.html', {'form': addform})
        else:
            return redirect('users:login')

    def post(self, request):
        addform = PostForm(request.POST, request.FILES)

        if addform.is_valid():
            add_blog = addform.save(commit=False)
            add_blog.author = request.user
            addform.save()
            messages.success(request, "Blog posted!")
            return redirect('posts:dashboard')
        else:
            messages.error(request, "Error posting blog!")
            return render(request, 'posts/add-blog.html', {'form': addform})

class UpdateBlogPost(TemplateView):
    template_name = 'posts/edit_post.html'

    def get(self, request, id):

        post = Post.objects.get(id=id)
        data = {
            'title': post.title,
            'content': post.content,
            'picture': post.picture
        }
        form = UpdatePostForm(initial=data)
        context = {
            'post': post,
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request, id):

        post = Post.objects.get(id=id)
        form = UpdatePostForm(request.POST, request.FILES, instance= post)

        if form.is_valid():
            form = form.save(commit=False)

            form.save()
            messages.success(request, "Blog updated!", extra_tags="update")
            return redirect('posts:postDetail', post.id)

        else:
            form = UpdatePostForm()
            messages.error(request, "Error updating!")
            return redirect('posts:postEdit', post.id)

def delete_Post(request, id):

    post = Post.objects.get(id=id)

    if post.author == request.user:
        post.delete()
        messages.success(request, "Post successfully deleted!")
        return HttpResponseRedirect(reverse('posts:dashboard'))

    return render(request, 'posts/delete_post.html')

def LikeView(request, id):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    if post.likes.filter(id = request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return HttpResponseRedirect(reverse('posts:postDetail', args=[id]))

class PostDetailView(TemplateView):
    template_name = 'posts/post_detail.html'

    def get(self, request, id):
        post = get_object_or_404(Post, id=id)
        totalLikes = post.total_likes()
        profile_list = User.objects.all()
        isLiked = False
        form = CommentForm()

        if post.likes.filter(id = request.user.id).exists():
            isLiked = True
        context = {
            'totalLikes': totalLikes,
            'isLiked' : isLiked,
            'profile_list' : profile_list,
            'post': post,
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request, id):
        post = Post.objects.get(id=id)
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('posts:postDetail', post.id)

        else:
            form = CommentForm()
            messages.error(request, "Invalid comment!", extra_tags='invalid_comment')
            return redirect('posts:postDetail', post.id)
        

templates/posts/add-blog.html
{% extends 'base.html' %}

{% block content %}
<h1>Create Post</h1>
<form action="{% url 'posts:add-blog' %}" method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" id="submit">Create Post</button>
</form>
{% for msg in messages %}
<div class="alert alert-danger" role="alert">
    {{ msg }}
  </div>
  {% endfor %}
{% endblock %}

templates/posts/delete_post.html
{% extends 'base.html' %}
<h1>Create Post</h1>
{% block content %}
<h3>Delete: {{ post.title }} </h3>
<strong>Confirm to delete this post?</strong>
<div class="form-group">
    <form action="{% url 'posts:postDelete' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Delete Post</button>
    </form>
</div>
{% endblock %}

templates/posts/edit_post.html
{% extends 'base.html' %}
{% block content %}
<h1>Edit Post</h1>
<div class='align-center'>
    <br><br>
    <div class="form-group">
        <form action="{% url 'posts:postEdit' post.id %}" method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <button class ="btn btn-secondary">Update Post</button>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<header class="py-5 bg-light border-bottom mb-4">
    <div class="container">
        <div class="text-center my-5">
            <h4>Django-blogs</h4>
            {% if user.is_authenticated %}
            <p>Have an Idea for a blog? <a href="{% url 'posts:add-blog' %}">Post it!</a>
            {% else %}
            <p>You are not logged in. You must log in to create a blog post.</p>
            <a href="{% url 'users:login' %}">Log In</a>
            {% endif %}
        </div>
    </div>
</header>

{% for msg in messages %}
{% if user.is_authenticated %}
<div class="alert alert-success" role="alert">
    {{ msg }}
  </div>
  {% else %}
<div class="alert alert-info" role="alert">
    {{ msg }}
  </div>
{% endif %}

  {% endfor %}

<div class="row">
    {% for post in posts %}
    <div class="col-4 py-3">
        <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{post.title}}</h5>
            {% for user in profile_list %}
                {% if user == post.author %}
                <small>Posted by <a href="{% url 'users:profile' user.id%}"> <strong>{{user.first_name}} {{user.last_name}}</strong> </a> at {{ post.date_created }}</small>
                {% endif %}
            {% endfor %}
            <p class="card-text">{{post.intro}}</p>
            <img src="{{post.picture.url}}" class="img-fluid"></img>
        </div>
        <div class="card-footer">
            <a class="btn btn-primary" href="{% url 'posts:postDetail' post.id %}" role="button">Read More</a>
        </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}
{% for msg in messages %}
        {% if "update" in msg.tags %}
            <div class="alert alert-success" role="alert">
                {{ msg }}
            </div>
        {% elif "invalid_comment" in msg.tags %}
            <div class="alert alert-danger" role="alert">
                {{ msg }}
            </div>
        {% endif %}
    {% endfor %}

    <div class ="text-center">
    <img src="{{post.picture.url}}" class="img-fluid"></img>
    </div>
    <h1 class="title">{{post.title}}</h1>
    {% for profile in profile_list %}
        {% if profile == post.author %}
        <small>Posted by <a href="{% url 'users:profile' profile.id%}">{{profile.first_name}} {{profile.last_name}}</a> at {{ post.date_created }}</small>
        {% endif %}
    {% endfor %}

    <p>{{ post.content }}</p>
    <hr>

    <h2 class="subtitle">Comments</h2>
    {% for comment in post.comments.all %}
            <article class="media">
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>{{ comment.author }}</strong> <small>{{ comment.date_added }}</small>
                            <br>
                            {{ comment.content }}
                        </p>
                    </div>
                </div>
            </article>
        {% empty %}
            <div class="notification">
                <p>No comments yet!</p>
            </div>
        {% endfor %}
    
{% if user.is_authenticated and user == post.author%}
    <a class="btn btn-primary" href="{% url 'posts:postEdit' post.id  %}">Edit Post</a>
    <a class="btn btn-danger" href="{% url 'posts:postDelete' post.id  %}">Delete Post</a>
    <p>Commenting as <strong>{{user}}</strong></p>
    <h3 class="subtitle">Add comment</h3>
        <form method="post" action="." novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <div class="field">
                <div class="control">
                    <button class="button is-success">Submit</button>
                </div>
            </div>
        </form>
        <form action="{% url 'posts:like_post' post.id %}" method='POST'>
            {% csrf_token %}
            {% if isLiked %}
                <button type='submit', name='post_id', value='{{post.id}}',
                class ="btn btn-danger btn-sm">Unlike</button>
            {% else %}
                <button type='submit', name='post_id', value='{{post.id}}',
                class ="btn btn-primary btn-sm">Like</button>
            {% endif %}
{% elif user.is_authenticated %}
    <p>Commenting as <strong>{{user}}</strong></p>
    <h3 class="subtitle">Add comment</h3>
        <form method="post" action="." novalidate>
            {% csrf_token %}
            {{ form.as_p }}

            <div class="field">
                <div class="control">
                    <button class="button is-success">Submit</button>
                </div>
            </div>
        </form>
    <br>
        <form action="{% url 'posts:like_post' post.id %}" method='POST'>
            {% csrf_token %}
            {% if isLiked %}
                <button type='submit', name='post_id', value='{{post.id}}',
                class ="btn btn-danger btn-sm">Unlike</button>
            {% else %}
                <button type='submit', name='post_id', value='{{post.id}}',
                class ="btn btn-primary btn-sm">Like</button>
            {% endif %}
            - {{ totalLikes }} Likes
{% else %}
    <p>You are not logged in. You must log in to comment, like and modify own posts.</p>
    <a href="{% url 'users:login' %}">Log In</a>
{% endif %}
{% endblock %}