core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include("django.contrib.auth.urls")),
    path('', include('posts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import DashboardView, AddBlogPost, UpdateBlogPost, PostDetailView, delete_Post, LikeView

app_name= 'posts'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('<int:id>/', PostDetailView.as_view(), name='postDetail'),
    path('<int:id>/update_post', UpdateBlogPost.as_view(), name='postEdit'),
    path('<int:id>/delete_post', delete_Post, name='postDelete'),
    path('<int:id>/like', LikeView, name='like_post'),
    path('add-blog/', AddBlogPost.as_view(), name='add-blog'),
]

users/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from users.views import IndexView, LoginView, LogoutView, RegisterView, ProfileView, ModifyProfileView, followToggle

app_name = 'users'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('login/', LoginView.as_view(), name='login'),
    path('profile/<int:id>/', ProfileView.as_view(), name='profile'),
    path('modifyProfile/', ModifyProfileView.as_view(), name='modifyProfile'),
    path('logout/', LogoutView, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('followToggle/<int:id>/', followToggle, name='followToggle')
]

templates/base.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>{% block title %}Blog{% endblock %}</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >  
    <script src="{% static 'bootstrap.min.js' %}"></script>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Blog</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'posts:dashboard' %}">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:profile' user.id%}">Profile</a>
              </li>
              {% endif %}
              {% if not user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
              </li>
              {% endif %}
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
              </li>
            </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
              {% endif %}
            </ul>
          </div>
            <span class="navbar-text">
              {{user.email}}
            </span>
        </div>
      </nav>

</head>  

<body>
  <main>
    <section class="section">
      <div class="container">

          {% block content %}
          {% endblock %}
            
      </div>
    </section>
  </main>  
</body>  
</html>  