core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include("django.contrib.auth.urls")),
    path('', include('posts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import DashboardView, AddBlogPost, UpdateBlogPost, PostDetailView, delete_Post, LikeView

app_name= 'posts'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('<int:id>/', PostDetailView.as_view(), name='postDetail'),
    path('<int:id>/update_post', UpdateBlogPost.as_view(), name='postEdit'),
    path('<int:id>/delete_post', delete_Post, name='postDelete'),
    path('<int:id>/like', LikeView, name='like_post'),
    path('add-blog/', AddBlogPost.as_view(), name='add-blog'),
]

users/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from users.views import IndexView, LoginView, LogoutView, RegisterView, ProfileView, ModifyProfileView, followToggle

app_name = 'users'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('login/', LoginView.as_view(), name='login'),
    path('profile/<int:id>/', ProfileView.as_view(), name='profile'),
    path('modifyProfile/', ModifyProfileView.as_view(), name='modifyProfile'),
    path('logout/', LogoutView, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('followToggle/<int:id>/', followToggle, name='followToggle')
]

users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from django.db import models
from django.db.models.signals import post_save

from django.dispatch import receiver
from django.utils import timezone

from rest_framework.authtoken.models import Token
from users.manager import UserManager

# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    """ Overrides Django Base User. """

    #username = None
    email = models.EmailField(max_length=500, unique=True)
    first_name = models.CharField(max_length=80, null=True, blank=True)
    last_name = models.CharField(max_length=80, null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    avatar = models.ImageField(blank=True, null=True, upload_to='profile_images', default='defaultAvatar.png')
    date_joined = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    following = models.ManyToManyField("self", related_name="followers", symmetrical=False)

    USERNAME_FIELD = "email"
    objects = UserManager()

    def __str__(self):
        return "{}".format(self.email)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model

User = get_user_model()
class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "password1", "password2")

class UpdateUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, widget=forms.TextInput)
    first_name=forms.CharField(label='First Name')
    last_name=forms.CharField(label='Last Name')
    avatar = forms.ImageField(label='Profile Picture',widget=forms.FileInput)

    class Meta:
        model = User
        fields = ['email','first_name', 'last_name', 'avatar']

class LoginForm(forms.Form):
    email = forms.CharField(label='Email', required=True, max_length=150)
    password = forms.CharField(label='Password', widget =forms.PasswordInput())

    field = (
        'email',
        'password'
    )

    def auth(self, request):

        auth_email = self.cleaned_data.get('email')
        pword = self.cleaned_data.get('password')
        return authenticate(request, email=auth_email, password=pword)

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import TemplateView
from .forms import LoginForm, RegisterForm, UpdateUserForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from .models import User
from posts.models import Post

# Create your views here.
class IndexView(TemplateView):
    template_name = 'users/index.html'

    def get(self, request):
        return render(request, self.template_name)

class RegisterView(TemplateView):
    template_name = 'users/register.html'

    def get(self, request):
        form = RegisterForm(request.POST)
        return render(request, self.template_name, {'form' : form})

    def post(self, request):
        form = RegisterForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password2'])
            user.save()
            email = request.POST['email']
            password = request.POST['password2']
            
            user = authenticate(request, email=email, password=password)
            messages.success(request, 'Your account is now registered try logging in.')
            return redirect('posts:dashboard')
        
        else:
            form = RegisterForm(request.POST)
            messages.error(request, 'Invalid Input!')
            return render(request, 'users/register.html', {'form': form})

class LoginView(TemplateView):

    template_name = 'users/login.html'

    def get(self, request):
        form = LoginForm()
        return render(request,'users/login.html', {'form' : form})

    def post(self, request):
        form = LoginForm(request.POST)

        #import pdb; pdb.set_trace()

        if form.is_valid():
            
            #passes email and pass, and authenticates it
            username = request.POST['email']
            password = request.POST['password']

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, 'Successfully Logged In!')
                return HttpResponseRedirect(reverse_lazy('posts:dashboard'))
            else:
                form = LoginForm(request.POST)
                messages.error(request, 'Please enter correct Email and Password!')
                return render(request, 'users/login.html', {'form' : form})
        
        else:
            messages.error(request, 'Please enter correct Email and Password!')
            return render(request, 'users/login.html', {'form': form})


class ProfileView(TemplateView):
    template_name='users/profile.html'

    #gets posts of user logged in and profile details of user
    def get(self, request, id):
        posts = Post.objects.filter(author=id)
        profile = get_object_or_404(User, id=id)
        isFollowed = False
        if profile.following.filter(id = request.user.id).exists():
            isFollowed = True
        context = {
            'posts' : posts,
            'profile' : profile,
            'isFollowed': isFollowed
        }
        return render(request, self.template_name, context)
    
def followToggle(request, id):
    user = get_object_or_404(User, id=request.POST.get('user_id'))
    if user.following.filter(id = request.user.id).exists():
        user.following.remove(request.user)
    else:
        user.following.add(request.user)
    return HttpResponseRedirect(reverse('users:profile', args=[id]))

def LogoutView(request):
    logout(request)
    messages.success(request, 'Account Logged Out!')
    return redirect('posts:dashboard')

class ModifyProfileView(TemplateView):
    template_name='users/modifyProfile.html'

    def get(self, request):
        form = UpdateUserForm()
        return render(request, 'users/modifyProfile.html', {'form' : form})
    
    def post(self, request):
        #get profile of user currently logged in
        profileUser = User.objects.get(id=request.user.id)
        profile_form = UpdateUserForm(request.POST, request.FILES, instance=profileUser)

        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profile has been updated successfully!')
            return redirect('users:profile')

        else:
            form = UpdateUserForm()
            messages.error(request, 'Invalid Input!')
            return render(request, 'users/modifyProfile.html', {'form' : form})

templates/users/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
  <h1>Hello there {{ user.first_name }} {{ user.last_name }}!</h1>
  <p>First Name: {{ user.first_name }}</p>
  <p>Last Name: {{ user.last_name}}</p>
  <p>Email: {{ user.email }}</p>
  <p><a href="{% url 'users:logout' %}">Log Out</a></p>
  
{% else %}
  <p>You are not logged in.</p>
  <a href="{% url 'users:login' %}">Log In</a>
  <br>
  <p>Don't have an account? Register <a href="{% url 'users:register' %}"> here!</a></p>
{% endif %}
{% endblock %}

{% block title %}Home{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
<h1>Login</h1>
<form action="{% url 'users:login' %}" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" id="submit">Login</button>
</form>
<br>
{% for msg in messages %}
<div class="alert alert-danger" role="alert">
    {{ msg }}
</div>
{% endfor %}
{% endblock %}

templates/users/modifyProfile.html
{% extends 'base.html' %}
<h1>Modify Profile</h1>
{% block content %}
<form action="{% url 'users:modifyProfile' %}" method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" id="submit">Update Profile</button>
</form>
<br>
{% for msg in messages %}
<div class="alert alert-danger" role="alert">
    {{ msg }}
  </div>
{% endfor %}
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{profile.first_name}}'s Profile{% endblock title %}
{% block content %}


<section class="h-100 gradient-custom-2">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card">
            <div class="rounded-top text-white d-flex flex-row" style="background-color: #4d94ff; height:200px;">
              <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                <img src="{{profile.avatar.url}}"
                  class="img-fluid img-thumbnail mt-4 mb-2"
                  style="max-height:120px;width:130px;">
                  <br>
                
              </div>
              <div class="ms-3" style="margin-top: 130px;">
                <h5>{{profile.first_name}} {{ profile.last_name}}</h5>
                <p>Followers: {{ profile.following.count }} | Following: {{ profile.followers.count }}</p>
              </div>
            </div>
            <div class="p-4 text-black" style="background-color: #f8f9fa;">
              <div class="d-flex justify-content-end text-center py-1">
                <div>
                  {% if user.is_authenticated and user == profile%}
                <a href="{% url 'users:modifyProfile' %}"class="btn btn-outline-dark" data-mdb-ripple-color="dark"
                  style="z-index: 1;">
                  Edit profile
                </a>
                {% elif user.is_authenticated %}
                <form action="{% url 'users:followToggle' profile.id %}" method='POST'>
                  {% csrf_token %}
                  {% if isFollowed %}
                      <button type='submit' class="btn btn-outline-dark" style="z-index: 1;" data-mdb-ripple-color="dark", name='user_id', value='{{profile.id}}',
                      class ="btn btn-danger btn-sm">Unfollow</button>
                  {% else %}
                      <button type='submit' class="btn btn-outline-dark" style="z-index: 1;" data-mdb-ripple-color="dark", name='user_id', value='{{profile.id}}',
                      class ="btn btn-primary btn-sm">Follow</button>
                  {% endif %}
                {% else %}
                <a href="{% url 'users:login' %}"class="btn btn-outline-dark" data-mdb-ripple-color="dark"
                  style="z-index: 1;">
                  Login
                </a>
                {% endif %}
                </div>
                <div class="px-3">

                </div>
                <div>

                </div>
              </div>
            </div>
            <div class="card-body p-4 text-black">
              <div class="d-flex justify-content-between align-items-center mb-4">
                <p class="lead fw-normal mb-0">Blogs</p>
              </div>
              <div class="row g-2">
                <div class="col mb-2">
                    {% for post in posts %}
                    <div class="post block">
                        <h2 class="subtitle">{{post.title}}</h2>
            
                        <small>Posted by {{post.author}} at {{ post.date_created }}</small>
            
                        <p>{{post.intro}}</p>
                        <a href="{% url 'posts:postDetail' post.id %}">Read More</a>
                    </div>
                {% endfor %}
                </div>
              </div>
            </div>

            <div class="card-body p-4 text-black">
              <div class="d-flex justify-content-between align-items-center mb-4">
                <p class="lead fw-normal mb-0">Followers</p>
              </div>
              <div class="row g-2">
                <div class="col mb-2">
                    {% for p in profile.following.all %}
                    <div class="post block">
                        <a href="{% url 'users:profile' p.id %}">{{p.email}}</a>
                    </div>
                {% endfor %}
                </div>
              </div>
            </div>
            <div class="card-body p-4 text-black">
              <div class="d-flex justify-content-between align-items-center mb-4">
                <p class="lead fw-normal mb-0">Following</p>
              </div>
              <div class="row g-2">
                <div class="col mb-2">
                    {% for p in profile.followers.all %}
                    <div class="post block">
                        <a href="{% url 'users:profile' p.id %}">{{p.email}}</a>
                    </div>
                {% endfor %}
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </section>
  <br>
  {% for msg in messages %}
<div class="alert alert-success" role="alert">
    {{ msg }}
  </div>
{% endfor %}

  {% endblock content %}

templates/users/register.html
{% extends 'base.html' %}
{% block content %}
<h1>Register</h1>

<form action="{% url 'users:register' %}" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" id="submit">Register</button>
</form>
<br>
{% for msg in messages %}
<div class="alert alert-danger" role="alert">
    {{ msg }}
  </div>
{% endfor %}
{%  endblock %}